# Basic php7.2 et apache
version: '3.1'

services:
  apache_php:
    image: php:7.2-apache
    restart: always
    expose:
      - '80'
    ports:
      - 80:80
    volumes:
      # Specify an absolute path mapping
      - /var/www/html:/var/www/html

