# Use root/example as user/password credentials
# CREATE USER 'user'@'%' IDENTIFIED BY 'user';
# GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
# flush privileges;
version: '3.1'

services:
  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      # Specify an absolute path mapping
      - /var/lib/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf