# Postgresql
version: '3.1'

services:
  postgresql:
    image: mdillon/postgis
    restart: always
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: pg
    ports:
      - 5432:5432
    volumes:
      # Specify an absolute path mapping
      - /var/lib/postgresql/db:/var/lib/postgresql
      - /var/lib/postgresql/data:/var/lib/postgresql/data