version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_POSTGRES: 127.0.0.1
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: pg
      REDMINE_DB_DATABASE: redmine
      
      
