version: '3.1'

services:
  postgresql:
    image: mdillon/postgis
    restart: always
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: pg
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/db:/var/lib/postgresql
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  mongodb:
    image: mongo:4.0
    restart: always
    expose:
      - '27017'
    ports:
      - 27017:27017    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mongodb:/data/db

  apache_php:
    build:
      context: ../docker
      dockerfile: php7.2-extensions
    depends_on:
      - postgresql
      - mysql
      - mongodb
    restart: always
    expose:
      - '80'
    ports:
      - 80:80
    volumes:
      - ./../www:/var/www/html
